import Head from "next/head";
import AppLayout from "components/app/AppLayout";
import { useSelector } from "react-redux";
import { useDispatch } from "react-redux";
import { getSoldProducts } from "redux-store/products/most.slice";
import { getTopProductsAsync } from "redux-store/products/top.slice";
import React from "react";
import SectionCreator from "components/app/User-profile/SectionCreator";
// import TopAdsBox from "components/app/StickyContainer/TopAdsBox";
import { Avatar, Grid, Stack, Typography } from "@mui/material";
import ServiceCard from "components/general/Cards/ServiceCard";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const dispatch = useDispatch();
  const topProducts = useSelector((state) => state.topProducts.list);
  const isLoading = useSelector((state) => state.topProducts.isLoading);
  const soldProducts = useSelector((state) => state.mostSoldProducts.list);
  const categories = useSelector((state) => state.categories.list);
  const router = useRouter();

  React.useEffect(() => {
    dispatch(getTopProductsAsync());
    dispatch(getSoldProducts());
  }, []);

  return (
    <AppLayout>
      <Head>
        <title> Chegirma | Online magazin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack my={4}>
        <Grid container spacing={3}>
          {categories.map((item) => {
            return (
              <Grid key={item.uid} item xs={4} sm={3} md={2}>
                <Link href={`/category/${item.uid}`}>
                  <Stack alignItems="center">
                    <Avatar
                      src={item.avatar}
                      sx={{
                        width: "90px",
                        height: "90px",
                        cursor: "pointer",
                      }}
                    >
                      {item?.title[router?.locale][0]}
                    </Avatar>
                    <Typography
                      align="center"
                      color="text.main"
                      variant="string"
                      mt={1}
                    >
                      {item?.title[router?.locale]}
                    </Typography>
                  </Stack>
                </Link>
              </Grid>
            );
          })}
        </Grid>
      </Stack>
      <SectionCreator
        isLoading={isLoading}
        name="Top mahsulotlar"
        data={topProducts}
      />
      <SectionCreator
        isLoading={isLoading}
        name="KO'P SOTILGAN MAHSULOTLAR"
        data={soldProducts}
      />
      <Grid container spacing={2} mb={2}>
        <Grid item xs={12} md={4}>
          <ServiceCard
            image="/assets/services/truck.png"
            name="Qulay to`lov va tezrok eltuv"
            desc="O'zbekiston bo'ylab 24 soat ichida istalgan mahsulotni istalgan yerga eltib berish hizmati."
          />
        </Grid>
        <Grid item xs={12} md={4}>
          <ServiceCard
            image="/assets/services/agreement.png"
            name="Xavfsiz va ishonchli xaridlar"
            desc="Biz uchun mijozlarimizning ishonchi birinchi o'rinda turadi."
          />
        </Grid>
        <Grid item xs={12} md={4}>
          <ServiceCard
            image="/assets/services/dailiyservice.png"
            name="24 / 7 qo`llab quvvatlash"
            desc="Kunning istalgan qismida biz bilan bog'lanib, istalgan mahsulot haqida malumot olishingiz mumkin."
          />
        </Grid>
      </Grid>
    </AppLayout>
  );
}
